# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_core.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../01_core.ipynb 3
def say_hello(to):
    "Say hello to somebody"
    return f'Hello there {to}!'


# %% ../01_core.ipynb 4
def foo(): pass
